### PR TITLE
Dreamin' API

### PR DESCRIPTION
**Pull request by gr2m**
See current state at https://github.com/hoodiehq/hoodie-account-server/tree/api.

Open questions:
- when user account is unconfirmed, and user does `account.signIn()`, should it reject or resolve and return false for `account.isConfirmed()`?
- custom account properties: is this good? `account.profile.set / get` and `signUp({username: '..', password: '..', profile: {} }`
- I'm not yet happy with `changePassword`, `changeUsername`, `profile.get`, `profile.set`. I think `profile.get` with the optional `remote: true` is cool. But for the rest, I wonder if we should do `account.update({username: 'newjoe'}, 'currentpassword')` und `account.profile.update({name: 'New Joe McDoe'})`
- What about "signin by email only": https://medium.com/the-story/signing-in-to-medium-by-email-aacc21134fcd? How would our code ideally look for that
- I wonder if we could combine `requestPasswordReset`, `requestUsernameReminder`, .... into `account.request(what, options)`? `what` could be all kind of things, and plugins could register their own handlers. By default, we'd have `password-reset`, `username-reminder`, `confirmation`. But we could easily implement `session-token` for the "signin by email" use case. Or things like `upgrade:pro` ... ?
- Do we need an `.isUnauthenticated()` method? What it means is that you are signed in, but your session is not valid any more. 
- I still have to add the events, see the current ones at http://docs.hood.ie/en/techdocs/api/client/hoodie.account.html#accountevents
- I'd also like to add the admin APIs to manage user accounts, but that's lower prio

### CODE REVIEW

**Comment by nintra** [comment]
I currently "lazy confirm" users. If they choose to confirm by mail, I let them login and just remind them to confirm their email address. I read that this is a common approach now. So users don't have to switch between apps.

I like this api design. Seems easier to use. Finally you can add additional data to users. :)

I'm not sure about the secureWrite, secureRead approaches. I don't think it is okay to save the password of the current user for the whole session. Are other authentication libs constructed the same way?

**Comment by gr2m** [comment]
> I don't think it is okay to save the password of the current user for the whole session

I think the API is missleading here, we wouldn't save any password, it would only be used in one request, then thrown away. 

> If they choose to confirm by mail, I let them login and just remind them to confirm their email address

Great input, thanks!

**Comment by nintra** [comment]
I guess I just got it wrong. You don't need to save the password, you just ask the user everytime he makes an important change. Sry, my fault. Seems right.

**Comment by gr2m** [comment]
> you just ask the user everytime he makes an important change

I was also thinking about a ["sudo" mode like like GitHub has it](https://github.com/blog/1513-introducing-github-sudo-mode), where for a certain time you are authenticated and don't need to pass the password every single time. But I'd leave that idea for later. Passing the password every time should be good for now

**Comment by espy** [comment]
I just read through https://github.com/hoodiehq/discussion/issues/75#issuecomment-121233089 and was wondering whether it would make sense to not just have `signInWith()`, but also `signUpWith()`, since it's possible that some apps (like ubersicht) would be fine with just oAuth. So `signUpWith()` would create a new user object and could also take custom user data.

**Comment by gr2m** [comment]
my thought was that `signInWith()` automatically does the sign up, if the account does not exist yet. Usually, apps that support signing in with Facebook etc. don't differentiate between the two, do they?

**Comment by zoepage** [comment]
@gr2m That's the question, if we need to have both. Here you can find the defined use-cases: https://github.com/hoodiehq/discussion/issues/75#issuecomment-121233089

**Comment by gr2m** [comment]
@nintra @mikehedman fyi we discuss oAuth-specifics here as well: https://github.com/hoodiehq/discussion/issues/75#issuecomment-121377342 we'll merge discussions once we agree on things :)

**Comment by gr2m** [comment]
I've updated the API (extensively) based on feedback so far. I've left out all the oAuth integrations (`.signInWith(provider, options)`), as it's being discussed over here: https://github.com/hoodiehq/discussion/issues/75#issuecomment-121233089

Looking forward to more feedback <3

**Pull request closed without merging**
